apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
