apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readOnly
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs:
      - get
      - watch
      - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: readOnly-binding
subjects:
  - kind: User
    name: baolg
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: readOnly
  apiGroup: rbac.authorization.k8s.io

